const techs = [
    "React", "Vue", "Angular", "Node.js", "Express", "MongoDB", "GraphQL", "TypeScript", "Tailwind CSS", "Docker", "Kubernetes", "AWS", "Firebase", 
    "HTML", "CSS", "JavaScript", "jQuery", "Bootstrap", "Sass", "Less", "PostCSS", "Webpack", "Gulp", "Babel", "ESLint", "Prettier", "Nginx", "Apache", 
    "PHP", "Laravel", "Symfony", "CodeIgniter", "Zend Framework", "ASP.NET", "Ruby on Rails", "Django", "Flask", "Spring Boot", "Java", "Python", "C#", "C++", 
    "Go", "Rust", "Kotlin", "Swift", "Dart", "Objective-C", "SQL", "PostgreSQL", "MySQL", "SQLite", "Oracle", "SQL Server", "NoSQL", "Cassandra", "CouchDB", 
    "Couchbase", "Redis", "Neo4j", "Elasticsearch", "InfluxDB", "Memcached", "Firebase Realtime Database", "Firestore", "PouchDB", "RethinkDB", "MongoDB Atlas", 
    "GraphQL", "REST", "SOAP", "gRPC", "JSON", "XML", "AJAX", "Axios", "Fetch API", "WebSockets", "Service Workers", "IndexedDB", "Local Storage", 
    "Session Storage", "Cookies", "OAuth", "JWT", "OpenID Connect", "SAML", "LDAP", "Active Directory", "RBAC", "ABAC", "XACML", "Access Control Lists (ACL)", 
    "Firewall", "VPN", "IPSec", "SSL/TLS", "SSH", "Kerberos", "Public Key Infrastructure (PKI)", "Encryption", "Hashing", "Digital Signatures", "Certificate Authorities", 
    "Blockchains", "Cryptographic Protocols", "RSA", "AES", "DES", "3DES", "Blowfish", "Twofish", "RC4", "RC5", "RC6", "Elliptic Curve Cryptography (ECC)", "Diffie-Hellman", 
    "MD5", "SHA-1", "SHA-2", "SHA-3", "bcrypt", "scrypt", "Argon2", "Quantum Cryptography", "Homomorphic Encryption", "Zero-Knowledge Proofs", "Secure Multiparty Computation", 
    "Digital Forensics", "Penetration Testing", "Intrusion Detection Systems (IDS)", "Intrusion Prevention Systems (IPS)", "Security Information and Event Management (SIEM)", 
    "Endpoint Security", "Antivirus", "Malware Analysis", "Reverse Engineering", "OS Internals", "Process Management", "Memory Management", "File Systems", 
    "I/O Systems", "Device Drivers", "Concurrency", "Multithreading", "Synchronization", "Virtualization", "Containers", "Linux", "Windows", "macOS", "Unix", 
    "FreeBSD", "OpenBSD", "NetBSD", "Plan 9", "Minix", "Solaris", "Embedded Systems", "Real-Time Operating Systems (RTOS)", "Networking Protocols", "TCP/IP", "UDP", 
    "HTTP/HTTPS", "FTP", "SMTP", "IMAP", "POP3", "SNMP", "DNS", "DHCP", "NAT", "IP Addressing", "Subnetting", "VLANs", "Routing Protocols", "BGP", "OSPF", "RIP", 
    "EIGRP", "IS-IS", "Switching", "Ethernet", "Wi-Fi", "Bluetooth", "Zigbee", "LoRaWAN", "SDN", "NFV", "Network Security", "Firewalls", "IDS/IPS", "VPNs", 
    "Load Balancing", "Content Delivery Networks (CDN)", "Quality of Service (QoS)", "VoIP", "WebRTC", "Video Streaming", "Cloud Computing", "Serverless", 
    "Edge Computing", "Fog Computing", "IoT", "Big Data", "Data Warehousing", "Data Lakes", "Data Mining", "Machine Learning", "Deep Learning", "Natural Language Processing (NLP)", 
    "Computer Vision", "Reinforcement Learning", "Robotics", "AI Ethics", "Agile", "Scrum", "Kanban", "DevOps", "CI/CD", "Automation", "Testing", "Unit Testing", 
    "Integration Testing", "Functional Testing", "Performance Testing", "Security Testing", "Usability Testing", "Compatibility Testing", "Accessibility Testing", 
    "Test Automation", "Test-Driven Development (TDD)", "Behavior-Driven Development (BDD)", "Continuous Integration", "Continuous Deployment", "Continuous Delivery", 
    "Infrastructure as Code (IaC)", "Configuration Management", "Container Orchestration", "Monitoring", "Logging", "Alerting", "Observability", "Incident Management", 
    "Problem Management", "Change Management", "Release Management", "Project Management", "Product Management", "Software Development Lifecycle (SDLC)", 
    "System Design", "Architecture Patterns", "Design Patterns", "Microservices", "Monolithic Architecture", "Serverless Architecture", "Event-Driven Architecture", 
    "Domain-Driven Design (DDD)", "Test-Driven Development (TDD)", "Behavior-Driven Development (BDD)", "Model-View-Controller (MVC)", "Model-View-ViewModel (MVVM)", 
    "Clean Architecture", "Hexagonal Architecture", "CQRS", "Event Sourcing", "Data Structures", "Algorithms", "Complexity Analysis", "Dynamic Programming", "Graph Theory", 
    "Sorting Algorithms", "Search Algorithms", "Trees", "Binary Trees", "Binary Search Trees", "AVL Trees", "Red-Black Trees", "B-Trees", "Heaps", "Priority Queues", 
    "Hash Tables", "Linked Lists", "Doubly Linked Lists", "Stacks", "Queues", "Recursion", "Divide and Conquer", "Backtracking", "Greedy Algorithms", "Bit Manipulation", 
    "Number Theory", "String Algorithms", "Pattern Matching", "Computational Geometry", "Approximation Algorithms", "Parallel Algorithms", "Distributed Algorithms", 
    "Quantum Algorithms", "Approximation Algorithms", "Online Algorithms", "Randomized Algorithms", "Genetic Algorithms", "Simulated Annealing", "Tabu Search", 
    "Ant Colony Optimization", "Swarm Intelligence", "Artificial Neural Networks", "Genetic Programming", "Evolutionary Algorithms", "Reinforcement Learning", 
    "Deep Reinforcement Learning", "Self-Learning Algorithms", "Collaborative Filtering", "Content-Based Filtering", "Hybrid Recommender Systems"
  ];
export default techs;  